# Generated by Django 4.1.6 on 2023-02-12 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('gradient', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('places', models.ManyToManyField(to='places.place')),
            ],
        ),
    ]
