# Generated by Django 4.1.6 on 2023-02-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0002_remove_compilation_type_compilation_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='gradient',
        ),
        migrations.AddField(
            model_name='compilation',
            name='primary_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='compilation',
            name='secondary_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
