# Generated by Django 4.1.6 on 2023-02-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='display_name',
            field=models.CharField(max_length=2000),
        ),
    ]
