# Generated by Django 4.1.6 on 2023-03-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
    ]
